USE Formula1;
START TRANSACTION;
INSERT INTO constructors (constructor_id,constructor_ref,constructor_name,nationality,url,extra) VALUES ('1','mclaren','McLaren','British','http://en.wikipedia.org/wiki/McLaren',NULL),
 ('2','bmw_sauber','BMW Sauber','German','http://en.wikipedia.org/wiki/BMW_Sauber',NULL),
 ('3','williams','Williams','British','http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering',NULL),
 ('4','renault','Renault','French','http://en.wikipedia.org/wiki/Renault_F1',NULL),
 ('5','toro_rosso','Toro Rosso','Italian','http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso',NULL),
 ('6','ferrari','Ferrari','Italian','http://en.wikipedia.org/wiki/Scuderia_Ferrari',NULL),
 ('7','toyota','Toyota','Japanese','http://en.wikipedia.org/wiki/Toyota_Racing',NULL),
 ('8','super_aguri','Super Aguri','Japanese','http://en.wikipedia.org/wiki/Super_Aguri_F1',NULL),
 ('9','red_bull','Red Bull','Austrian','http://en.wikipedia.org/wiki/Red_Bull_Racing',NULL),
 ('10','force_india','Force India','Indian','http://en.wikipedia.org/wiki/Force_India',NULL),
 ('11','honda','Honda','Japanese','http://en.wikipedia.org/wiki/Honda_Racing_F1',NULL),
 ('12','spyker','Spyker','Dutch','http://en.wikipedia.org/wiki/Spyker_F1',NULL),
 ('13','mf1','MF1','Russian','http://en.wikipedia.org/wiki/Midland_F1_Racing',NULL),
 ('14','spyker_mf1','Spyker MF1','Dutch','http://en.wikipedia.org/wiki/Midland_F1_Racing',NULL),
 ('15','sauber','Sauber','Swiss','http://en.wikipedia.org/wiki/Sauber',NULL),
 ('16','bar','BAR','British','http://en.wikipedia.org/wiki/British_American_Racing',NULL),
 ('17','jordan','Jordan','Irish','http://en.wikipedia.org/wiki/Jordan_Grand_Prix',NULL),
 ('18','minardi','Minardi','Italian','http://en.wikipedia.org/wiki/Minardi',NULL),
 ('19','jaguar','Jaguar','British','http://en.wikipedia.org/wiki/Jaguar_Racing',NULL),
 ('20','prost','Prost','French','http://en.wikipedia.org/wiki/Prost_Grand_Prix',NULL),
 ('21','arrows','Arrows','British','http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International',NULL),
 ('22','benetton','Benetton','Italian','http://en.wikipedia.org/wiki/Benetton_Formula',NULL),
 ('23','brawn','Brawn','British','http://en.wikipedia.org/wiki/Brawn_GP',NULL),
 ('24','stewart','Stewart','British','http://en.wikipedia.org/wiki/Stewart_Grand_Prix',NULL),
 ('25','tyrrell','Tyrrell','British','http://en.wikipedia.org/wiki/Tyrrell_Racing',NULL),
 ('26','lola','Lola','British','http://en.wikipedia.org/wiki/MasterCard_Lola',NULL),
 ('27','ligier','Ligier','French','http://en.wikipedia.org/wiki/Ligier',NULL),
 ('28','forti','Forti','Italian','http://en.wikipedia.org/wiki/Forti',NULL),
 ('29','footwork','Footwork','British','http://en.wikipedia.org/wiki/Footwork_Arrows',NULL),
 ('30','pacific','Pacific','British','http://en.wikipedia.org/wiki/Pacific_Racing',NULL),
 ('31','simtek','Simtek','British','http://en.wikipedia.org/wiki/Simtek',NULL),
 ('32','team_lotus','Team Lotus','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('33','larrousse','Larrousse','French','http://en.wikipedia.org/wiki/Larrousse',NULL),
 ('34','brabham','Brabham','British','http://en.wikipedia.org/wiki/Brabham',NULL),
 ('35','dallara','Dallara','Italian','http://en.wikipedia.org/wiki/Dallara',NULL),
 ('36','fondmetal','Fondmetal','Italian','http://en.wikipedia.org/wiki/Fondmetal',NULL),
 ('37','march','March','British','http://en.wikipedia.org/wiki/March_Engineering',NULL),
 ('38','moda','Andrea Moda','Italian','http://en.wikipedia.org/wiki/Andrea_Moda_Formula',NULL),
 ('39','ags','AGS','French','http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives',NULL),
 ('40','lambo','Lambo','Italian','http://en.wikipedia.org/wiki/Modena_(racing_team)',NULL),
 ('41','leyton','Leyton House','British','http://en.wikipedia.org/wiki/Leyton_House',NULL),
 ('42','coloni','Coloni','Italian','http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems',NULL),
 ('44','eurobrun','Euro Brun','Italian','http://en.wikipedia.org/wiki/Euro_Brun',NULL),
 ('45','osella','Osella','Italian','http://en.wikipedia.org/wiki/Osella',NULL),
 ('46','onyx','Onyx','British','http://en.wikipedia.org/wiki/Onyx_(racing_team)',NULL),
 ('47','life','Life','Italian','http://en.wikipedia.org/wiki/Life_(Racing_Team)',NULL),
 ('48','rial','Rial','German','http://en.wikipedia.org/wiki/Rial_%28racing_team%29',NULL),
 ('49','zakspeed','Zakspeed','German','http://en.wikipedia.org/wiki/Zakspeed',NULL),
 ('50','ram','RAM','British','http://en.wikipedia.org/wiki/RAM_Racing',NULL),
 ('51','alfa','Alfa Romeo','Italian','http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)',NULL),
 ('52','spirit','Spirit','British','http://en.wikipedia.org/wiki/Spirit_(racing_team)',NULL),
 ('53','toleman','Toleman','British','http://en.wikipedia.org/wiki/Toleman',NULL),
 ('54','ats','ATS','Italian','http://en.wikipedia.org/wiki/ATS_(wheels)',NULL),
 ('55','theodore','Theodore','Hong Kong','http://en.wikipedia.org/wiki/Theodore_Racing',NULL),
 ('56','fittipaldi','Fittipaldi','Brazilian','http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29',NULL),
 ('57','ensign','Ensign','British','http://en.wikipedia.org/wiki/Ensign_%28racing_team%29',NULL),
 ('58','shadow','Shadow','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars',NULL),
 ('59','wolf','Wolf','Canadian','http://en.wikipedia.org/wiki/Walter_Wolf_Racing',NULL),
 ('60','merzario','Merzario','Italian','http://en.wikipedia.org/wiki/Merzario',NULL),
 ('61','kauhsen','Kauhsen','German','http://en.wikipedia.org/wiki/Kauhsen',NULL),
 ('62','rebaque','Rebaque','Mexican','http://en.wikipedia.org/wiki/Rebaque',NULL),
 ('63','surtees','Surtees','British','http://en.wikipedia.org/wiki/Surtees',NULL),
 ('64','hesketh','Hesketh','British','http://en.wikipedia.org/wiki/Hesketh_Racing',NULL),
 ('65','martini','Martini','French','http://en.wikipedia.org/wiki/Martini_(cars)',NULL),
 ('66','brm','BRM','British','http://en.wikipedia.org/wiki/BRM',NULL),
 ('67','penske','Penske','American','http://en.wikipedia.org/wiki/Penske_Racing',NULL),
 ('68','lec','LEC','British','http://en.wikipedia.org/wiki/LEC_(Formula_One)',NULL),
 ('69','mcguire','McGuire','Australian','http://en.wikipedia.org/wiki/McGuire_(Formula_One)',NULL),
 ('70','boro','Boro','Dutch','http://en.wikipedia.org/wiki/Boro_(Formula_One)',NULL),
 ('71','apollon','Apollon','Swiss','http://en.wikipedia.org/wiki/Apollon_(Formula_One)',NULL),
 ('72','kojima','Kojima','Japanese','http://en.wikipedia.org/wiki/Kojima_Engineering',NULL),
 ('73','parnelli','Parnelli','American','http://en.wikipedia.org/wiki/Parnelli',NULL),
 ('74','maki','Maki','Japanese','http://en.wikipedia.org/wiki/Maki_(cars)',NULL),
 ('75','hill','Embassy Hill','British','http://en.wikipedia.org/wiki/Hill_(constructor)',NULL),
 ('76','lyncar','Lyncar','British','http://en.wikipedia.org/wiki/Lyncar',NULL),
 ('77','trojan','Trojan','British','http://en.wikipedia.org/wiki/Trojan_(Racing_team)',NULL),
 ('78','amon','Amon','New Zealand','http://en.wikipedia.org/wiki/Amon_(Formula_One_team)',NULL),
 ('79','token','Token','British','http://en.wikipedia.org/wiki/Token_(Racing_team)',NULL),
 ('80','iso_marlboro','Iso Marlboro','British','http://en.wikipedia.org/wiki/Iso_Marlboro',NULL),
 ('81','tecno','Tecno','Italian','http://en.wikipedia.org/wiki/Tecno',NULL),
 ('82','matra','Matra','French','http://en.wikipedia.org/wiki/Matra',NULL),
 ('83','politoys','Politoys','British','http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars',NULL),
 ('84','connew','Connew','British','http://en.wikipedia.org/wiki/Connew',NULL),
 ('85','bellasi','Bellasi','Swiss','http://en.wikipedia.org/wiki/Bellasi',NULL),
 ('86','tomaso','De Tomaso','Italian','http://en.wikipedia.org/wiki/De_Tomaso',NULL),
 ('87','cooper','Cooper','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('88','eagle','Eagle','American','http://en.wikipedia.org/wiki/Anglo_American_Racers',NULL),
 ('89','lds','LDS','South African','http://en.wikipedia.org/wiki/LDS_(automobile)',NULL),
 ('90','protos','Protos','British','http://en.wikipedia.org/wiki/Protos_(constructor)',NULL),
 ('91','shannon','Shannon','British','http://en.wikipedia.org/wiki/Shannon_(Formula_One)',NULL),
 ('92','scirocco','Scirocco','British','http://en.wikipedia.org/wiki/Scirocco-Powell',NULL),
 ('93','re','RE','Rhodesian','http://en.wikipedia.org/wiki/RE_%28automobile%29',NULL),
 ('94','brp','BRP','British','http://en.wikipedia.org/wiki/British_Racing_Partnership',NULL),
 ('95','porsche','Porsche','German','http://en.wikipedia.org/wiki/Porsche_in_Formula_One',NULL),
 ('96','derrington','Derrington','British','http://en.wikipedia.org/wiki/Derrington-Francis',NULL),
 ('97','gilby','Gilby','British','http://en.wikipedia.org/wiki/Gilby',NULL),
 ('98','stebro','Stebro','Canadian','http://en.wikipedia.org/wiki/Stebro',NULL),
 ('99','emeryson','Emeryson','British','http://en.wikipedia.org/wiki/Emeryson',NULL),
 ('100','enb','ENB','Belgium','http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge',NULL),
 ('101','jbw','JBW','British','http://en.wikipedia.org/wiki/JBW',NULL),
 ('102','ferguson','Ferguson','British','http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.',NULL),
 ('103','mbm','MBM','Swiss','http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors',NULL),
 ('104','behra-porsche','Behra-Porsche','Italian','http://en.wikipedia.org/wiki/Behra-Porsche',NULL),
 ('105','maserati','Maserati','Italian','http://en.wikipedia.org/wiki/Maserati',NULL),
 ('106','scarab','Scarab','American','http://en.wikipedia.org/wiki/Scarab_(constructor)',NULL),
 ('107','watson','Watson','American','http://en.wikipedia.org/wiki/A.J._Watson',NULL),
 ('108','epperly','Epperly','American','http://en.wikipedia.org/wiki/Epperly',NULL),
 ('109','phillips','Phillips','American','http://en.wikipedia.org/wiki/Phillips_(constructor)',NULL),
 ('110','lesovsky','Lesovsky','American','http://en.wikipedia.org/wiki/Lesovsky',NULL),
 ('111','trevis','Trevis','American','http://en.wikipedia.org/wiki/Trevis',NULL),
 ('112','meskowski','Meskowski','American','http://en.wikipedia.org/wiki/Meskowski',NULL),
 ('113','kurtis_kraft','Kurtis Kraft','American','http://en.wikipedia.org/wiki/Kurtis_Kraft',NULL),
 ('114','kuzma','Kuzma','American','http://en.wikipedia.org/wiki/Kuzma_(constructor)',NULL),
 ('115','vhristensen','Christensen','American','http://en.wikipedia.org/wiki/Christensen_(constructor)',NULL),
 ('116','ewing','Ewing','American','http://en.wikipedia.org/wiki/Ewing_(constructor)',NULL),
 ('117','aston_martin','Aston Martin','British','http://en.wikipedia.org/wiki/Aston_Martin',NULL),
 ('118','vanwall','Vanwall','British','http://en.wikipedia.org/wiki/Vanwall',NULL),
 ('119','moore','Moore','American','http://en.wikipedia.org/wiki/Moore_(constructor)',NULL),
 ('120','dunn','Dunn','American','http://en.wikipedia.org/wiki/Dunn_Engineering',NULL),
 ('121','elder','Elder','American','http://en.wikipedia.org/wiki/Elder_(constructor)',NULL),
 ('122','sutton','Sutton','American','http://en.wikipedia.org/wiki/Sutton_(constructor)',NULL),
 ('123','fry','Fry','British','http://en.wikipedia.org/wiki/Fry_(racing_team)',NULL),
 ('124','tec-mec','Tec-Mec','Italian','http://en.wikipedia.org/wiki/Tec-Mec',NULL),
 ('125','connaught','Connaught','British','http://en.wikipedia.org/wiki/Connaught_Engineering',NULL),
 ('126','alta','Alta','British','http://en.wikipedia.org/wiki/Alta_auto_racing_team',NULL),
 ('127','osca','OSCA','Italian','http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili',NULL),
 ('128','gordini','Gordini','French','http://en.wikipedia.org/wiki/Gordini',NULL),
 ('129','stevens','Stevens','American','http://en.wikipedia.org/wiki/Stevens_(constructor)',NULL),
 ('130','bugatti','Bugatti','French','http://en.wikipedia.org/wiki/Bugatti',NULL),
 ('131','mercedes','Mercedes','German','http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One',NULL),
 ('132','lancia','Lancia','Italian','http://en.wikipedia.org/wiki/Lancia_in_Formula_One',NULL),
 ('133','hwm','HWM','British','http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors',NULL),
 ('134','schroeder','Schroeder','American','http://en.wikipedia.org/wiki/Schroeder_(constructor)',NULL),
 ('135','pawl','Pawl','American','http://en.wikipedia.org/wiki/Pawl_(constructor)',NULL),
 ('136','pankratz','Pankratz','American','http://en.wikipedia.org/wiki/Pankratz',NULL),
 ('137','arzani-volpini','Arzani-Volpini','Italian','http://en.wikipedia.org/wiki/Arzani-Volpini',NULL),
 ('138','nichels','Nichels','American','http://en.wikipedia.org/wiki/Nichels',NULL),
 ('139','bromme','Bromme','American','http://en.wikipedia.org/wiki/Bromme',NULL),
 ('140','klenk','Klenk','German','http://en.wikipedia.org/wiki/Klenk',NULL),
 ('141','simca','Simca','French','http://en.wikipedia.org/wiki/Simca',NULL),
 ('142','turner','Turner','American','http://en.wikipedia.org/wiki/Turner_(constructor)',NULL),
 ('143','del_roy','Del Roy','American','http://en.wikipedia.org/wiki/Del_Roy',NULL),
 ('144','veritas','Veritas','German','http://en.wikipedia.org/wiki/Veritas_(constructor)',NULL),
 ('145','bmw','BMW','German','http://en.wikipedia.org/wiki/BMW',NULL),
 ('146','emw','EMW','East German','http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk',NULL),
 ('147','afm','AFM','German','http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau',NULL),
 ('148','frazer_nash','Frazer Nash','British','http://en.wikipedia.org/wiki/Frazer_Nash',NULL),
 ('149','sherman','Sherman','American','http://en.wikipedia.org/wiki/Sherman_(constructor)',NULL),
 ('150','deidt','Deidt','American','http://en.wikipedia.org/wiki/Deidt',NULL),
 ('151','era','ERA','British','http://en.wikipedia.org/wiki/English_Racing_Automobiles',NULL),
 ('152','butterworth','Aston Butterworth','British','http://en.wikipedia.org/wiki/Aston_Butterworth',NULL),
 ('153','cisitalia','Cisitalia','Italian','http://en.wikipedia.org/wiki/Cisitalia',NULL),
 ('154','lago','Talbot-Lago','French','http://en.wikipedia.org/wiki/Talbot-Lago',NULL),
 ('155','hall','Hall','American','http://en.wikipedia.org/wiki/Hall_(constructor)',NULL),
 ('156','marchese','Marchese','American','http://en.wikipedia.org/wiki/Marchese_(constructor)',NULL),
 ('157','langley','Langley','American','http://en.wikipedia.org/wiki/Langley_(constructor)',NULL),
 ('158','rae','Rae','American','http://en.wikipedia.org/wiki/Rae_(motorsport)',NULL),
 ('159','olson','Olson','American','http://en.wikipedia.org/wiki/Olson_(constructor)',NULL),
 ('160','wetteroth','Wetteroth','American','http://en.wikipedia.org/wiki/Wetteroth',NULL),
 ('161','adams','Adams','American','http://en.wikipedia.org/wiki/Adams_(constructor)',NULL),
 ('162','snowberger','Snowberger','American','http://en.wikipedia.org/wiki/Snowberger',NULL),
 ('163','milano','Milano','Italian','http://en.wikipedia.org/wiki/Scuderia_Milano',NULL),
 ('164','hrt','HRT','Spanish','http://en.wikipedia.org/wiki/Hispania_Racing',NULL),
 ('167','cooper-maserati','Cooper-Maserati','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('166','virgin','Virgin','British','http://en.wikipedia.org/wiki/Virgin_Racing',NULL),
 ('168','cooper-osca','Cooper-OSCA','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('169','cooper-borgward','Cooper-Borgward','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('170','cooper-climax','Cooper-Climax','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('171','cooper-castellotti','Cooper-Castellotti','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('172','lotus-climax','Lotus-Climax','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('173','lotus-maserati','Lotus-Maserati','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('174','de_tomaso-osca','De Tomaso-Osca','Italian','http://en.wikipedia.org/wiki/De_Tomaso',NULL),
 ('175','de_tomaso-alfa_romeo','De Tomaso-Alfa Romeo','Italian','http://en.wikipedia.org/wiki/De_Tomaso',NULL),
 ('176','lotus-brm','Lotus-BRM','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('177','lotus-borgward','Lotus-Borgward','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('178','cooper-alfa_romeo','Cooper-Alfa Romeo','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('179','de_tomaso-ferrari','De Tomaso-Ferrari','Italian','http://en.wikipedia.org/wiki/De_Tomaso',NULL),
 ('180','lotus-ford','Lotus-Ford','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('181','brabham-brm','Brabham-BRM','British','http://en.wikipedia.org/wiki/Brabham',NULL),
 ('182','brabham-ford','Brabham-Ford','British','http://en.wikipedia.org/wiki/Brabham',NULL),
 ('183','brabham-climax','Brabham-Climax','British','http://en.wikipedia.org/wiki/Brabham',NULL),
 ('184','lds-climax','LDS-Climax','South African','http://en.wikipedia.org/wiki/LDS_(automobile)',NULL),
 ('185','lds-alfa_romeo','LDS-Alfa Romeo','South African','http://en.wikipedia.org/wiki/LDS_(automobile)',NULL),
 ('186','cooper-ford','Cooper-Ford','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('187','mclaren-ford','McLaren-Ford','British','http://en.wikipedia.org/wiki/Team_McLaren',NULL),
 ('188','mclaren-seren','McLaren-Serenissima','British','http://en.wikipedia.org/wiki/Team_McLaren',NULL),
 ('189','eagle-climax','Eagle-Climax','American','http://en.wikipedia.org/wiki/Anglo_American_Racers',NULL),
 ('190','eagle-weslake','Eagle-Weslake','American','http://en.wikipedia.org/wiki/Anglo_American_Racers',NULL),
 ('191','brabham-repco','Brabham-Repco','British','http://en.wikipedia.org/wiki/Brabham',NULL),
 ('192','cooper-ferrari','Cooper-Ferrari','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('193','cooper-ats','Cooper-ATS','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('194','mclaren-brm','McLaren-BRM','British','http://en.wikipedia.org/wiki/McLaren_(racing)',NULL),
 ('195','cooper-brm','Cooper-BRM','British','http://en.wikipedia.org/wiki/Cooper_Car_Company',NULL),
 ('196','matra-ford','Matra-Ford','French','http://en.wikipedia.org/wiki/Matra',NULL),
 ('197','brm-ford','BRM-Ford','British','http://en.wikipedia.org/wiki/BRM',NULL),
 ('198','mclaren-alfa_romeo','McLaren-Alfa Romeo','British','http://en.wikipedia.org/wiki/McLaren_(racing)',NULL),
 ('199','march-alfa_romeo','March-Alfa Romeo','British','http://en.wikipedia.org/wiki/March_Engineering',NULL),
 ('200','march-ford','March-Ford','British','http://en.wikipedia.org/wiki/March_Engineering',NULL),
 ('201','lotus-pw','Lotus-Pratt &amp; Whitney','British','http://en.wikipedia.org/wiki/Team_Lotus',NULL),
 ('202','shadow-ford','Shadow-Ford','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars',NULL),
 ('203','shadow-matra','Shadow-Matra','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars',NULL),
 ('204','brabham-alfa_romeo','Brabham-Alfa Romeo','British','http://en.wikipedia.org/wiki/Brabham',NULL),
 ('205','lotus_racing','Lotus','Malaysian','http://en.wikipedia.org/wiki/Lotus_Racing',NULL),
 ('206','marussia','Marussia','Russian','http://en.wikipedia.org/wiki/Marussia_F1',NULL),
 ('207','caterham','Caterham','Malaysian','http://en.wikipedia.org/wiki/Caterham_F1',NULL),
 ('208','lotus_f1','Lotus F1','British','http://en.wikipedia.org/wiki/Lotus_F1',NULL),
 ('209','manor','Manor Marussia','British','http://en.wikipedia.org/wiki/Manor_Motorsport',NULL),
 ('210','haas','Haas F1 Team','American','http://en.wikipedia.org/wiki/Haas_F1_Team',NULL);
COMMIT;
